[package]
name = "procurator32"
version = "0.1.0"
edition = "2021"

[lib]
name = "shiori"
crate-type = ["cdylib"]

[dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_Globalization",
] }
