name = "my-ghost"
version = "0.1.0"

[[require]]
git = "https://github.com/rejafdofs/uka-lean"
rev = "master"
name = "uka-lean"

[[lean_lib]]
name = "Ghost"

[[lean_exe]]
name = "ghost"
root = "Principalis"
moreLinkArgs = ["-mconsole"]
